create database Grocery_Store_Management_db;
use  Grocery_Store_Management_db;

-- 1. Supplier Table

CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);
select * from supplier;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

select * from categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);
select * from employees;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);
select * from customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
select * from products;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
select * from orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
select * from order_details;

-- Analysis Questions
-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.




-- How many unique customers have placed orders?
select  count(distinct cust_id) as "Total customers placed orders" from orders;

-- Which customers have placed the highest number of orders?

SELECT 
    cust_id,
    cust_name,
    total_orders
FROM (
    SELECT 
        c.cust_id,
        c.cust_name,
        COUNT(o.ord_id) AS total_orders,
        RANK() OVER (ORDER BY COUNT(o.ord_id) DESC) AS rnk
    FROM customers c
    JOIN orders o
    ON c.cust_id = o.cust_id
    GROUP BY c.cust_id, c.cust_name
) t
WHERE rnk = 1;

-- What is the total and average purchase value per customer?

select c.cust_id,c.cust_name,sum(d.total_price) as "Total_purchase value per customer",avg(d.total_price) as 
"Average purchase value per customer " from customers as c join orders as o
on c.cust_id=o.cust_id join order_details as d on o.ord_id=d.ord_id group by c.cust_id,c.cust_name;


-- Who are the top 5 customers by total purchase amount?

select cust_id,cust_name from(
select c.cust_id,c.cust_name,sum(d.total_price) as "Total purchase amount", 
rank() over (order by sum(d.total_price) desc) as rnk
from customers as c join orders as o
on c.cust_id=o.cust_id join order_details as d on o.ord_id=d.ord_id group by c.cust_id,c.cust_name )
t where rnk <= 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

-- How many products exist in each category?
 
 select c.cat_id,c.cat_name,count(p.prod_id) as "products count on each category" from categories as c left join products as p on c.cat_id=p.cat_id 
 group by c.cat_id,c.cat_name;

-- What is the average price of products by category?
select c.cat_id,c.cat_name,avg(p.price) as "avg_price"from categories as c left join products as p on c.cat_id=p.cat_id 
 group by c.cat_id,c.cat_name;

-- Which products have the highest total sales volume (by quantity)?
select prod_id,prod_name from(
select p.prod_id,p.prod_name,count(o.quantity) , rank() over (order by count(o.quantity) desc) as rnk 
from products as p join order_details as o on p.prod_id=o.prod_id group by prod_id,prod_name)t
where rnk = 1;
 
-- What is the total revenue generated by each product?
select p.prod_id,p.prod_name,sum(od.total_price) as total_revenue from products as p join order_details as od
on p.prod_id=od.prod_id
 group by prod_id,prod_name order by total_revenue desc;


-- How do product sales vary by category and supplier?
select c.cat_name,s.sup_name,sum(od.total_price) as total_sales from order_details od join products p  
on od.prod_id = p.prod_id join categories c on p.cat_id = c.cat_id join supplier s on p.sup_id = s.sup_id
group by c.cat_name,s.sup_name order by total_sales desc;

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.

--- How many orders have been placed in total?
select count(*) as total_orders from orders;

-- What is the average value per order?
select  avg(order_total) as avg_order_value from (
    select ord_id,sum(total_price) as order_total from order_details
    group by ord_id
) t;

-- On which dates were the most orders placed?
select order_date,count(ord_id) as total_orders from orders
group by order_date order by total_orders desc;

-- What are the monthly trends in order volume and revenue?

-- what are the monthly trends in order volume and revenue?
select  date_format(str_to_date(o.order_date, '%y-%m-%d'), '%y-%m') as month,
count(distinct o.ord_id) as total_orders,sum(od.total_price) as total_revenue
from orders o join order_details od on o.ord_id = od.ord_id group by month order by month;

-- How do order patterns vary across weekdays and weekends?
select
    case
        when dayname(str_to_date(order_date, '%d-%m-%Y')) in ('saturday','sunday')
        then 'weekend'
        else 'weekday'
    end as day_type,
    count(ord_id) as total_orders
from orders
group by day_type;


-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.

-- How many suppliers are there in the database?
select count(*) as total_suppliers from supplier;


-- Which supplier provides the most products?
select s.sup_name,count(p.prod_id) as total_products from supplier s join products p on s.sup_id = p.sup_id
group by s.sup_name order by total_products desc limit 1;

-- What is the average price of products from each supplier?
select s.sup_id,s.sup_name, avg(p.price) as avg_price from supplier s
join products p on s.sup_id = p.sup_id
group by s.sup_id, s.sup_name order by avg_price desc;


-- Which suppliers contribute the most to total product sales (by revenue)?
select sup_id, sup_name, total_revenue
from (
    select 
        s.sup_id,
        s.sup_name,
        sum(d.total_price) as total_revenue,
        rank() over (order by sum(d.total_price) desc) as rnk
    from supplier s
    join products p 
        on s.sup_id = p.sup_id
    join order_details d 
        on p.prod_id = d.prod_id
    group by s.sup_id, s.sup_name
) t
where rnk = 1;


-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.

-- How many employees have processed orders?

select count(distinct e.emp_id) as total_employees_processed_orders
from employees e join orders o on e.emp_id = o.emp_id;

-- Which employees have handled the most orders?
select emp_id, emp_name, total_orders
from (
    select 
        e.emp_id,
        e.emp_name,
        count(o.ord_id) as total_orders,
        rank() over (order by count(o.ord_id) desc) as rnk
    from employees e
    join orders o
        on e.emp_id = o.emp_id
    group by e.emp_id, e.emp_name
) t
where rnk = 1;


-- What is the total sales value processed by each employee?
select 
    e.emp_id,
    e.emp_name,
    sum(d.total_price) as total_sales_value
from employees e
join orders o
    on e.emp_id = o.emp_id
join order_details d
    on o.ord_id = d.ord_id
group by e.emp_id, e.emp_name;


-- What is the average order value handled per employee?
select 
    e.emp_id,
    e.emp_name,
    sum(d.total_price) / count(distinct o.ord_id) as avg_order_value
from employees e
join orders o
    on e.emp_id = o.emp_id
join order_details d
    on o.ord_id = d.ord_id
group by e.emp_id, e.emp_name;


-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.

-- What is the relationship between quantity ordered and total price?
/* When the quantity ordered increases, the total price also increases.
This is because total price depends on how many items are purchased.
It helps understand sales and customer buying patterns */

select 
    prod_id,
    quantity,
    total_price
from order_details;


-- What is the average quantity ordered per product?
select 
    prod_id,
    avg(quantity) as avg_quantity
from order_details
group by prod_id;


-- How does the unit price vary across products and orders?
select 
    p.prod_id,
    p.prod_name,
    min(d.each_price) as min_unit_price,
    max(d.each_price) as max_unit_price,
    avg(d.each_price) as avg_unit_price
from products p
join order_details d
    on p.prod_id = d.prod_id
group by p.prod_id, p.prod_name;
